export const ScreenConst: any = {
    LOGIN_SCREEN: 'LOGIN SCREEN',
    LIST_VIEW_SCREEN: 'LIST VIEW SCREEN',
    ONBOARD_SCREEN_1: 'ONBOARD SCREEN 1',
    ONBOARD_SCREEN_2: 'ONBOARD SCREEN 2',
    ONBOARD_SCREEN_3: 'ONBOARD SCREEN 3',
}